name: 'JWT Generator with options'
description: 'Generate JWT tokens (JSON Web Tokens)'
author: 'sgoff0'
inputs:
  secret:
    description: 'The shared secret used to sign the JWTs'
  payload:
    description: 'The payload to encrypt'
outputs:
  token:
    description: 'Generated JWT Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'yellow'
